#!/bin/sh
cd waku-timeline-service
cabal update
cabal install --only-dependencies
cabal configure
cabal build
cp -f ./dist/build/waku-timeline-service/waku-timeline-service ../bin/waku-timeline-service_x86_64
cd ..
